### ISSUE TITLE
Do you plan to support the HDF5 input？

### ISSUE THREAD

**Issue by huyuhuster** [ufo-kit/tofu#108]
As the title.

**Comment by matze** [comment]
It is supported if ufo-filters was built with libhdf5 (`libhdf5-dev` on Ubuntu) present. Due to the nature of the format the filename convention is a bit special though and involves specifying the dataset path after a colon. For example, to copy images from one file to the next you would do

    ufo-launch read path=foo.h5:/bar ! write filename=qux.h5:/baz

But AFAIR there is no special support in tofu.
