### ISSUE TITLE
Wrong image dimensions with multi-tif sinograms

### ISSUE THREAD

**Issue by MarcusZuber** [ufo-kit/tofu#59]
`tofu sinos` creates a multi-tif if only one output file is specified. e.g.
`tofu sinos --projection-folder "proj/frame*.tif" --output "sinos.tif"`
When this tif file is used as a input for the tomo reconstruction
`tofu tomo --sinogram-folder "sinos.tif" --output "reco.tif" --axis 1000` or
`tofu tomo --sinogram-folder "sinos.tif" --output "reco_%04i.tif" --axis 1000`
the dimensions of the reconstructed slices are `n_projections` x `n_projections` and the reconstruction is not correct.

**Comment by matze** [comment]
Two things:

1. tofu is clever enough to reconstruct from a directory, i.e. you can omit the `frame*.tif` glob.
2. Reconstructing from a multi TIFF has some performance impact because the sinogram has to be read first and depending on the many libraries between us and the file system this might involve reading the entire file into memory.
